-- ============================================================
-- favorites table
-- Stores which users have favorited which items.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.favorites (
  -- UUID primary key; generated by the DB so the client never has to supply one
  id          uuid          PRIMARY KEY DEFAULT gen_random_uuid(),

  -- References auth.users so orphaned rows are impossible if a user is deleted
  user_id     uuid          NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- References the items table; favorite disappears when the item is deleted
  item_id     uuid          NOT NULL REFERENCES public.items(id) ON DELETE CASCADE,

  created_at  timestamptz   NOT NULL DEFAULT now(),

  -- A user can favorite a given item at most once
  CONSTRAINT favorites_user_item_unique UNIQUE (user_id, item_id)
);

-- Index on item_id lets us count/list who favorited a given item efficiently
CREATE INDEX IF NOT EXISTS idx_favorites_item_id ON public.favorites (item_id);

-- Composite index matches the most common read pattern: "is this item favorited by this user?"
-- (user_id, item_id) is already covered by the UNIQUE constraint; no extra index needed.

-- Enable RLS (policy file: rls.sql)
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
